// Thèmes complets (roue + page) proposés dans l'éditeur de roue, réutilisés pour les affiches.
export const TEMPLATES = [
  {
    id: "elegant", name: "Or Royal",
    desc: "Noir & or, sobre et luxueux",
    palette: ["#2A2A2E","#D4AF37","#F3E9D2","#3B3B40","#C9A84C","#8C7B5A","#1D1D1F","#E6C766"],
    primaryColor: "#1D1D1F", secondaryColor: "#C9A84C",
    wheelBorderColor: "#C9A84C", wheelCenterColor: "#FAFAFA", dividerColor: "#F3E9D2", pointerColor: "#C9A84C",
    ringWidth: 16, bulbs: true, bulbColor: "#FFF1C1",
    wheelFont: "Playfair Display", wheelSize: 360,
    bg: "#FAFAFA", bgType: "color", bgGradient: "",
    textColor: "#1D1D1F", btnColor: "#1D1D1F", btnRadius: 8,
    btnText: "",
    title: "Tournez et gagnez !",
    welcome: "Tentez votre chance et découvrez votre récompense exclusive.",
    thanks: "Merci ! Votre cadeau vous attend en caisse.",
    cardColor: "#F5F0E8",
  },
  {
    id: "festif", name: "Festif",
    desc: "Couleurs vives, festif",
    palette: ["#FF5D73","#FFC93C","#2ECC71","#3D8BFF","#FF6FC8","#8E5CF2","#FF9A3C","#00C2CB"],
    primaryColor: "#FF5D73", secondaryColor: "#FFC93C",
    wheelBorderColor: "#FFFFFF", wheelCenterColor: "#FFFFFF", dividerColor: "#FFFFFF", pointerColor: "#FF5D73",
    ringWidth: 14, bulbs: true, bulbColor: "#FFF3B0",
    wheelFont: "Nunito", wheelSize: 360,
    bg: "#7C3AED", bgType: "gradient", bgGradient: "linear-gradient(135deg, #7C3AED 0%, #EC4899 100%)",
    textColor: "#FFFFFF", btnColor: "#FFC93C", btnRadius: 999,
    btnText: "",
    title: "Tentez votre chance !",
    welcome: "Tournez la roue des cadeaux !",
    thanks: "Incroyable ! Votre cadeau vous attend !",
    cardColor: "rgba(255,255,255,0.12)",
  },
  {
    id: "minimaliste", name: "Minimal",
    desc: "Épuré, typographie moderne",
    palette: ["#18181B","#52525B","#A1A1AA","#3F3F46","#71717A","#D4D4D8","#27272A","#E4E4E7"],
    primaryColor: "#18181B", secondaryColor: "#71717A",
    wheelBorderColor: "#18181B", wheelCenterColor: "#F4F4F5", dividerColor: "#F4F4F5", pointerColor: "#18181B",
    ringWidth: 10, bulbs: false, bulbColor: "",
    wheelFont: "Inter", wheelSize: 340,
    bg: "#F4F4F5", bgType: "color", bgGradient: "",
    textColor: "#18181B", btnColor: "#18181B", btnRadius: 6,
    btnText: "",
    title: "Un cadeau pour vous.",
    welcome: "Tournez la roue et découvrez votre récompense.",
    thanks: "Merci. Présentez ce code en caisse.",
    cardColor: "#EBEBEB",
  },
  {
    id: "sombre", name: "Néon",
    desc: "Fond noir, accents néon",
    palette: ["#00E676","#00B8D4","#D500F9","#FF6D00","#651FFF","#1DE9B6","#FFD600","#FF1744"],
    primaryColor: "#00E676", secondaryColor: "#00B8D4",
    wheelBorderColor: "#1B1B2F", wheelCenterColor: "#0F0F1A", dividerColor: "#0F0F1A", pointerColor: "#00E676",
    ringWidth: 16, bulbs: true, bulbColor: "#7CFFC4",
    wheelFont: "Space Grotesk", wheelSize: 380,
    bg: "#0F0F1A", bgType: "color", bgGradient: "",
    textColor: "#FFFFFF", btnColor: "#00E676", btnRadius: 12,
    btnText: "",
    title: "Tournez. Gagnez.",
    welcome: "Tournez la roue et découvrez votre récompense.",
    thanks: "Votre cadeau vous attend !",
    cardColor: "rgba(255,255,255,0.07)",
  },
  {
    id: "nature", name: "Nature",
    desc: "Tons naturels, chaleureux",
    palette: ["#16A34A","#84CC16","#EAB308","#B45309","#0D9488","#4ADE80","#A3E635","#F59E0B"],
    primaryColor: "#16A34A", secondaryColor: "#84CC16",
    wheelBorderColor: "#166534", wheelCenterColor: "#F0FDF4", dividerColor: "#F0FDF4", pointerColor: "#16A34A",
    ringWidth: 14, bulbs: false, bulbColor: "",
    wheelFont: "DM Sans", wheelSize: 360,
    bg: "#F0FDF4", bgType: "color", bgGradient: "",
    textColor: "#14532D", btnColor: "#16A34A", btnRadius: 14,
    btnText: "",
    title: "Tournez et gagnez chez nous !",
    welcome: "Merci de nous soutenir. Tournez la roue et gagnez un cadeau !",
    thanks: "Merci ! Votre récompense vous attend avec le sourire.",
    cardColor: "#DCFCE7",
  },
  {
    id: "casino", name: "Casino",
    desc: "Rouge, noir & or, ampoules",
    palette: ["#C1121F","#111111","#C1121F","#111111","#C1121F","#111111","#C1121F","#111111"],
    primaryColor: "#C1121F", secondaryColor: "#111111",
    wheelBorderColor: "#D4AF37", wheelCenterColor: "#F3E9D2", dividerColor: "#D4AF37", pointerColor: "#D4AF37",
    ringWidth: 20, bulbs: true, bulbColor: "#FFF1C1",
    wheelFont: "Playfair Display", wheelSize: 370,
    bg: "#1A0A0C", bgType: "gradient", bgGradient: "radial-gradient(circle at 50% 0%, #4A1018 0%, #1A0A0C 70%)",
    textColor: "#FFFFFF", btnColor: "#D4AF37", btnRadius: 10,
    btnText: "",
    title: "Tentez votre chance !",
    welcome: "Tournez la roue et découvrez votre gain.",
    thanks: "Félicitations ! Votre gain vous attend.",
    cardColor: "rgba(255,255,255,0.08)",
  },
  {
    id: "ocean", name: "Océan",
    desc: "Bleus profonds et turquoise",
    palette: ["#0077B6","#00B4D8","#0096C7","#48CAE4","#023E8A","#2EC4B6","#0A9396","#90E0EF"],
    primaryColor: "#0077B6", secondaryColor: "#00B4D8",
    wheelBorderColor: "#03396C", wheelCenterColor: "#F0FBFF", dividerColor: "#F0FBFF", pointerColor: "#00B4D8",
    ringWidth: 14, bulbs: false, bulbColor: "",
    wheelFont: "Nunito", wheelSize: 360,
    bg: "#EAF8FF", bgType: "gradient", bgGradient: "linear-gradient(180deg, #D9F1FF 0%, #F4FBFF 100%)",
    textColor: "#023E8A", btnColor: "#0077B6", btnRadius: 14,
    btnText: "",
    title: "Plongez dans la chance !",
    welcome: "Tournez la roue et repartez avec un cadeau.",
    thanks: "Bravo ! Votre cadeau vous attend.",
    cardColor: "#D9F1FF",
  },
  {
    id: "sunset", name: "Sunset",
    desc: "Dégradés orange, rose, violet",
    palette: ["#FF7A18","#FF3D6E","#B5179E","#FFB400","#F72585","#7209B7","#FF5400","#FF9E00"],
    primaryColor: "#FF3D6E", secondaryColor: "#FF7A18",
    wheelBorderColor: "#FFFFFF", wheelCenterColor: "#FFF7ED", dividerColor: "#FFF7ED", pointerColor: "#FF3D6E",
    ringWidth: 14, bulbs: true, bulbColor: "#FFF3B0",
    wheelFont: "Nunito", wheelSize: 360,
    bg: "#FF7A18", bgType: "gradient", bgGradient: "linear-gradient(160deg, #FF7A18 0%, #FF3D6E 55%, #7209B7 100%)",
    textColor: "#FFFFFF", btnColor: "#FFFFFF", btnRadius: 999,
    btnText: "",
    title: "Votre cadeau vous attend !",
    welcome: "Tournez la roue et voyez ce que vous gagnez.",
    thanks: "Bravo ! Votre cadeau est prêt.",
    cardColor: "rgba(255,255,255,0.16)",
  },
  {
    id: "bonbon", name: "Bonbon",
    desc: "Pastel doux et arrondi",
    palette: ["#FF8FAB","#B8E1FF","#FFD6A5","#CDB4DB","#B9FBC0","#FFC8DD","#A2D2FF","#FDFFB6"],
    primaryColor: "#FF8FAB", secondaryColor: "#A2D2FF",
    wheelBorderColor: "#FFFFFF", wheelCenterColor: "#FFFFFF", dividerColor: "#FFFFFF", pointerColor: "#FF8FAB",
    ringWidth: 16, bulbs: true, bulbColor: "#FFFFFF",
    wheelFont: "Nunito", wheelSize: 360,
    bg: "#FFF0F5", bgType: "gradient", bgGradient: "linear-gradient(180deg, #FFE5EC 0%, #F1F7FF 100%)",
    textColor: "#5C3D5E", btnColor: "#FF8FAB", btnRadius: 999,
    btnText: "",
    title: "Un petit cadeau ?",
    welcome: "Tournez la roue, c'est tout doux et c'est offert.",
    thanks: "Youpi ! Votre cadeau vous attend.",
    cardColor: "#FFFFFF",
  },
];
